image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'
    
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{%appveyor_build_version%}'
  assembly_file_version: '{%appveyor_build_version%}'
  assembly_informational_version: '{%appveyor_build_version%}'
  
build:
  project: .\CsToTs.sln
  verbosity: minimal
  
before_build:
  - dotnet restore

after_build:
- dotnet pack src\CsToTs\CsToTs.csproj -c Release /p:Version=%appveyor_build_version%
- appveyor PushArtifact src\CsToTs\bin\Release\CsToTs.%appveyor_build_version%.nupkg

test_script:
- dotnet test -c %CONFIGURATION% tests\CsToTs.Tests\CsToTs.Tests.csproj
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test -f netcoreapp2.0 -c %CONFIGURATION% tests/CsToTs.Tests/CsToTs.Tests.csproj" -filter:"+[CsToTs*]* -[CsToTs.*Tests*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -output:opencoverCoverage.xml -oldStyle -register:user
- nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
- .\tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken "%COVERALLS_REPO_TOKEN%" --useRelativePaths --commitId "%APPVEYOR_REPO_COMMIT%" --commitBranch "%APPVEYOR_REPO_BRANCH%" --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId "%APPVEYOR_BUILD_NUMBER%" --serviceName appveyor

deploy:
  provider: NuGet
  api_key:
    secure: hQY0HMU8ADJvqFfivG/Z0+h2Nz8xFCFd64ERHhaTFc3SzRy3Kz8C3FE8tiJMqMjz
  skip_symbols: false
  artifact: /.CsToTs*\.nupkg/
  on:
    appveyor_repo_tag: true
